# Generated by Django 5.2.3 on 2025-06-13 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='€/t', max_length=20)),
                ('category', models.CharField(default='Autre', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IndexValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='main.index')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reference_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('fixed', 'Fixe (non indexé)'), ('indexed', 'Indexé')], max_length=10)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('fixed_amount', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(help_text='Nom de la tranche (ex: énergie, transport...)', max_length=100)),
                ('index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.index')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slices', to='main.part')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.CharField(choices=[('free', 'Gratuit'), ('pack_5', 'Pack 5 index'), ('pack_10', 'Pack 10 index'), ('premium', 'Premium')], default='free', max_length=20)),
                ('primary_index_change_count', models.PositiveIntegerField(default=0)),
                ('favorite_indexes', models.ManyToManyField(blank=True, to='main.index')),
                ('primary_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_primary_index', to='main.index')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
