# Generated by Django 5.2.3 on 2025-06-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexvalue',
            name='date',
        ),
        migrations.AddField(
            model_name='indexvalue',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_values', to='main.part'),
        ),
        migrations.AlterField(
            model_name='indexvalue',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.index'),
        ),
    ]
