# Generated by Django 5.2.3 on 2025-06-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_indexvalue_date_indexvalue_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexvalue',
            name='part',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='index_values', to='main.part'),
            preserve_default=False,
        ),
    ]
