# Generated by Django 5.0.2 on 2025-05-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_valid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Gratuit'), ('pack_5', 'Pack 5 index'), ('pack_10', 'Pack 10 index'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
