# Generated by Django 5.0.2 on 2025-05-23 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userprofile_subscription_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='primary_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_primary_index', to='main.index'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_index_change_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
