# Generated by Django 5.2.3 on 2025-06-13 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_indexvalue_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexvalue',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
