# Generated by Django 5.2.3 on 2025-06-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_indexvalue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexvalue',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.part'),
        ),
    ]
