# Generated by Django 5.0.2 on 2025-05-28 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile_primary_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedPriceStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.FloatField(help_text='Prix de base à la date de référence')),
                ('reference_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_structures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StructureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('fixed', 'Fixe (non indexé)'), ('indexed', 'Indexé')], max_length=10)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('fixed_amount', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(help_text="Nom de la tranche (e.g. main d'œuvre, énergie)", max_length=100)),
                ('index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.index')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='main.indexedpricestructure')),
            ],
        ),
    ]
