# Generated by Django 5.2.3 on 2025-06-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_indexvalue_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reference_date',
        ),
    ]
