# Generated by Django 5.0.2 on 2025-06-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_indexedpricestructure_structurecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurecomponent',
            name='use_percentage',
            field=models.BooleanField(default=False),
        ),
    ]
