# Generated by Django 5.2.3 on 2025-06-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='reference_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de référence'),
        ),
    ]
