# Generated by Django 5.0.2 on 2025-06-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_structurecomponent_use_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='unit',
            field=models.CharField(default='€', max_length=50),
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
