# Generated by Django 5.2.3 on 2025-06-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_slice_reference_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
