# Generated by Django 5.0.2 on 2025-06-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_index_unit_alter_index_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='index',
            name='unit',
            field=models.CharField(default='€/t', max_length=20),
        ),
    ]
