# Generated by Django 5.0.2 on 2025-06-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_index_name_alter_index_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='category',
            field=models.CharField(default='Autre', max_length=50),
        ),
    ]
