# Generated by Django 5.2.3 on 2025-06-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_reference_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='reference_price',
            field=models.FloatField(default=1000, help_text='Prix à la date de référence', verbose_name='Prix de référence (€)'),
            preserve_default=False,
        ),
    ]
