# Generated by Django 5.0.2 on 2025-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('5_index', '5 Index'), ('10_index', '10 Index'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
