# Generated by Django 5.0.2 on 2025-07-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userprofile_subscription_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='primary_index_change_count',
            new_name='favorite_changes_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='primary_index',
        ),
    ]
