# Generated by Django 5.0.2 on 2025-07-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_primary_index_change_count_userprofile_favorite_changes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='category',
            field=models.CharField(default='Autre', max_length=255),
        ),
    ]
