# Generated by Django 5.0.2 on 2025-07-06 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_index_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='index',
            name='category',
            field=models.CharField(choices=[('batiment', 'Bâtiment et Construction'), ('energie', 'Énergie'), ('matiere_premiere', 'Matières Premières'), ('transport', 'Transport et Logistique'), ('main_oeuvre', "Main d'œuvre"), ('equipement', 'Équipement et Machines'), ('service', 'Services'), ('agriculture', 'Agriculture'), ('metaux', 'Métaux'), ('chimie', 'Chimie et Pétrochimie'), ('textile', 'Textile'), ('alimentaire', 'Industrie Alimentaire'), ('Inflation', 'Inflation'), ('autre', 'Autre')], default='autre', help_text="Catégorie de l'index", max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='main.product'),
        ),
    ]
