# Generated by Django 5.0.2 on 2025-08-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='criteria_unit',
            field=models.CharField(blank=True, help_text='Unité du critère (ex: tonnes, m², m³, kg...)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='criteria_value',
            field=models.FloatField(blank=True, help_text='Valeur du critère (ex: 2.5 pour 2.5 tonnes)', null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='slice_mode',
            field=models.CharField(choices=[('percentage', 'Cost Structure (%)'), ('fixed_criteria', 'Fixed Criteria')], default='percentage', help_text='Mode de calcul de la tranche', max_length=20),
        ),
    ]
