# Generated by Django 5.0.2 on 2025-08-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_slice_criteria_unit_slice_criteria_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slice',
            name='criteria_unit',
        ),
        migrations.RemoveField(
            model_name='slice',
            name='criteria_value',
        ),
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='criteria_value_tonnes',
            field=models.FloatField(blank=True, help_text='Value in tonnes (ex: 2.5 tonnes)', null=True),
        ),
    ]
