"""
Django settings for django_project project.
Generated by 'django-admin startproject' using Django 5.0.1.
For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Charger les variables d'environnement depuis .env (uniquement en local)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# 🔒 SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if os.environ.get('DEBUG', 'True').lower() == 'true':
        # Générer une clé temporaire pour le développement
        import secrets
        SECRET_KEY = secrets.token_urlsafe(50)
        print("⚠️ Utilisation d'une SECRET_KEY temporaire pour le développement")
    else:
        raise ValueError("❌ SECRET_KEY environment variable is required in production!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# ALLOWED_HOSTS compatible avec Replit et Railway
ALLOWED_HOSTS = []
if os.environ.get('ALLOWED_HOSTS'):
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS').split(',')
    # Nettoyer les espaces et points-virgules
    ALLOWED_HOSTS = [host.strip().rstrip(';') for host in ALLOWED_HOSTS]
else:
    # Hosts par défaut pour dev
    ALLOWED_HOSTS = [".replit.dev", ".replit.app", "localhost", "127.0.0.1"]

# Ajout automatique du domaine Railway si présent
if os.environ.get('RAILWAY_STATIC_URL'):
    railway_domain = os.environ.get('RAILWAY_STATIC_URL').replace('https://', '').replace('http://', '').rstrip(';')
    ALLOWED_HOSTS.append(railway_domain)

# 🔍 DEBUG: Afficher toutes les variables d'environnement CSRF (temporaire)
print("🔍 DEBUG VARIABLES D'ENVIRONNEMENT:")
print(f"📊 CSRF_TRUSTED_ORIGINS brute: {repr(os.environ.get('CSRF_TRUSTED_ORIGINS'))}")
print(f"🚂 RAILWAY_STATIC_URL: {repr(os.environ.get('RAILWAY_STATIC_URL'))}")
print(f"🏠 ALLOWED_HOSTS brute: {repr(os.environ.get('ALLOWED_HOSTS'))}")
print("="*50)

# CSRF trusted origins - TEST ULTIME
if os.environ.get('RAILWAY_STATIC_URL'):
    # On est sur Railway - TEST avec une string complètement neuve
    url_clean = "https://index-tracker-production.up.railway.app"
    CSRF_TRUSTED_ORIGINS = [url_clean]
    print(f"🚂 RAILWAY DETECTÉ - URL clean: {repr(url_clean)}")
    print(f"🧪 TEST: Length = {len(url_clean)}, ends with ';' = {url_clean.endswith(';')}")
    print(f"🔬 CSRF final type: {type(CSRF_TRUSTED_ORIGINS[0])}")
    print(f"🔬 CSRF final repr: {repr(CSRF_TRUSTED_ORIGINS[0])}")
    print(f"🔬 CSRF final len: {len(CSRF_TRUSTED_ORIGINS[0])}")
elif os.environ.get('CSRF_TRUSTED_ORIGINS'):
    # Variable d'environnement définie - nettoyer les points-virgules
    CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS').split(',')
    CSRF_TRUSTED_ORIGINS = [origin.strip().rstrip(';') for origin in CSRF_TRUSTED_ORIGINS]
    print("🌐 VARIABLE CSRF DETECTÉE - nettoyage des points-virgules")
else:
    # On est en local
    CSRF_TRUSTED_ORIGINS = [
        "https://*.replit.dev", 
        "https://*.replit.app",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]
    print("🏠 LOCAL DETECTÉ - CSRF configuré pour Replit")

print(f"📝 CSRF_TRUSTED_ORIGINS final: {CSRF_TRUSTED_ORIGINS}")
print("="*50)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin', 
    'django.contrib.auth',
    'django.contrib.contenttypes', 
    'django.contrib.sessions',
    'django.contrib.messages', 
    'django.contrib.staticfiles', 
    'main',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Pour les fichiers statiques
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

# Only use clickjacking protection in deployments because the Development Web View uses
# iframes and needs to be a cross origin.
if ("REPLIT_DEPLOYMENT" in os.environ) or not DEBUG:
    MIDDLEWARE.append('django.middleware.clickjacking.XFrameOptionsMiddleware')

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'main' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.index_list',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'

# Database - Configuration automatique PostgreSQL/SQLite
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR}/db.sqlite3',
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'en-us'  
TIME_ZONE = 'Europe/Paris'  # Changé pour Paris
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'main', 'static'),
]

# Pour la production (Railway), collecte des fichiers statiques
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuration WhiteNoise pour optimiser les fichiers statiques
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configuration des médias
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'

# Configuration Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ✉️ CONFIGURATION EMAIL
# Configuration email pour Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Variables d'environnement à configurer dans Railway
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'indextracker.contact@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  # Mot de passe d'application Gmail
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'indextracker.contact@gmail.com')

# Pour le développement local, vous pouvez aussi utiliser la console
if DEBUG and not os.environ.get('EMAIL_HOST_PASSWORD'):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("📧 Mode développement: emails affichés dans la console")

# Paramètres de sécurité pour la production
if not DEBUG:
    # HTTPS obligatoire en production - DÉSACTIVÉ temporairement pour Railway
    # SECURE_SSL_REDIRECT = True  # ← Commenté car Railway gère déjà HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Sécurité des cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Protection contre les attaques
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

    # Préférences de contenu sécurisé
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Configuration des logs pour Railway
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'main': {  # Logs de votre app
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}